services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - backend_net
      - frontend_net
    restart: always

  ollama:
    image: ollama/ollama
    networks:
      - backend_net

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/Neo4j@2026!
    networks:
      - backend_net

  milvus:
    image: milvusdb/milvus:v2.4.4
    command: ["milvus","run","standalone"]
    networks:
      - backend_net

networks:
  backend_net:
  frontend_net: