# FINAL Runtime Image — JDK 21.0.5
FROM eclipse-temurin:21.0.5_11-jre

WORKDIR /app

# 由 deploy.sh 传入 jar
ARG JAR_FILE=app.jar
COPY ${JAR_FILE} /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java","-Xms256m","-Xmx768m","-jar","/app/app.jar"]