events {}

http {

  upstream agent {
    server agent_blue:8080;
  }

  server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # ===== 前端 =====
    location / {
      try_files $uri $uri/ /index.html;
    }

    # ===== 后端 API =====
    location /chat/ {
      proxy_pass http://agent;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}